package com.cricket;

public class CricketFields {
    public enum Field {
        BATTING_AVERAGE,STRIKE_RATE,SIXES,FOURS,SIXES_AND_FOURS,STRIKERATE_WITH_SIXES_AND_FOURS,AVERAGE_WITH_STRIKERATE,
        RUNS_WITH_AVERAGE,BOWLING_AVERAGE,BOWLING_STRIKERATE,ECONOMY_RATE,AVERAGE_WITH_WICKETS,BOWLING_AVERAGE_WITH_STRIKERATE,
        BOWLING_AVERAGE_AND_BATTING_AVERAGE,BATTING_RUNS_AND_WICKETS;
    }
}
